[build-system]
requires = ["pip>=24", "setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "lavague"
version = "1.0.0"
description = "Selenium code generation from text instructions"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
keywords = ["IA", "AI", "selenium", "generation"]
authors = [
  {name = "Mithril Security", email = "contact@mithrilsecurity.io" }
]
maintainers = [
  {name = "Mithril Security", email = "contact@mithrilsecurity.io" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: Apache License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "llama_index",
  "llama-index-embeddings-huggingface",
  "llama-index-llms-huggingface",
  "llama-index-retrievers-bm25",
  "tree-sitter",
  "tree-sitter-languages",
  "nest_asyncio",
  "selenium",
  "google-search-results",
  "bitsandbytes",
  "python-dotenv"
]

[project.optional-dependencies]
dev = ["ruff", "ipykernel", "gradio"]

[project.urls]
"Homepage" = "https://mithrilsecurity.io"
"Bug Reports" = "https://github.com/lavague-ai/LaVague/issues"
"Source" = "https://github.com/lavague-ai/LaVague/"
