name: Python Code Check in docs and README

on:
  push:
    paths:
      - 'lavague-core/**'
      - 'lavague-integrations/**'
      - '_lavague/**'
      - 'lavague-gradio/**'
      - 'pyproject.toml'
      - '.github/workflows/docs-code.yaml'
      - '.github/new-code-check.py'
    
jobs:
  check-code:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Extract Python code from README.md
      # Remove headless=False if it is present
      run: |
        sed -n '/```python/,/```/p' README.md | sed '/```*/d' | sed 's/headless=False//g' > check-code.py

    - name: Install dependencies
      run: |
        pip install ./lavague-core
        pip install ./lavague-integrations/contexts/lavague-contexts-gemini
        pip install ./lavague-integrations/contexts/lavague-contexts-openai
        pip install ./lavague-integrations/drivers/lavague-drivers-selenium
        pip freeze | grep lavague
        git log | head -1

    - name: Check code consistency with docs/index.md
      run: |
        if ! diff -wu <(sed -n '/```python/,/```/p' README.md | sed '/```*/d') <(sed -n '/```python/,/```/p' docs/index.md | sed '/```*/d'); then
          echo "The Python code blocks in README.md and docs/index.md do not match."
          exit 1
        fi

    - name: Replace OpenAI with Gemini
      run: |
        sed -i 's/action_engine = ActionEngine(selenium_driver)/from lavague.contexts.gemini import GeminiContext\ngemini_context = GeminiContext()\naction_engine = ActionEngine.from_context(selenium_driver, gemini_context)/' check-code.py
        sed -i 's/agent = WebAgent(world_model, action_engine)/world_model = WorldModel.from_context(gemini_context)\nagent = WebAgent(world_model, action_engine)/' check-code.py
    
    - name: Check code
      run: cat check-code.py
    
    - name: Run the Python script
      run: python check-code.py

    # - name: Install nbconvert
    #   run: pip install notebook nbconvert

    # # Run quick tour with local code not pypi package
    # - name: Skip install from pypi
    #   run: |
    #     notebook_path="docs/docs/get-started/quick-tour-notebook/quick-tour.ipynb"
    #     sed -i '0,/^!pip install lavague$/s/^!pip install lavague$/# &/' "$notebook_path"

    # - name: Execute the notebook
    #   run: |
    #     jupyter nbconvert --to notebook --execute --inplace --output "quick-tour.ipynb" "docs/docs/get-started/quick-tour-notebook/quick-tour.ipynb"